### ISSUE TITLE
what value should pass to 'http_path' in project.yaml file?

### ISSUE THREAD

**Issue by shwangdev** [cloudera/dbt-impala-example#8]
Hi team,

What value I should pass to 'http_path' in this projects.yaml?

```

dbt_impala_demo:
  outputs:
    dev:
     type: impala
     host: <impala host>
     port: <impala port>
     dbname: <db name>
     schema: <db name>
     user: <user>
     password: <password>
     auth_type: ldap
     use_http_transport: true
     use_ssl: true
     http_path: <http path>
  target: dev
```
